# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oms_gateway.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'oms_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11oms_gateway.proto\x12\nomsgateway\"P\n\x0cReadyMessage\x12\x11\n\tcomponent\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12\r\n\x05ts_ms\x18\x04 \x01(\x03\"\xb7\x01\n\x0cOrderCommand\x12\x0e\n\x06\x63md_id\x18\x01 \x01(\t\x12&\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x16.omsgateway.ActionType\x12\x0e\n\x06oms_id\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x0c\n\x04side\x18\x05 \x01(\t\x12\x10\n\x08quantity\x18\x06 \x01(\x05\x12\r\n\x05price\x18\x07 \x01(\x01\x12\x0f\n\x07gateway\x18\x08 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\t \x01(\t\"\xfa\x01\n\nOrderEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0e\n\x06oms_id\x18\x02 \x01(\t\x12\x14\n\x0c\x65vent_source\x18\x03 \x01(\t\x12\x12\n\nevent_type\x18\x04 \x01(\t\x12\x0e\n\x06symbol\x18\x05 \x01(\t\x12\x0c\n\x04side\x18\x06 \x01(\t\x12\x10\n\x08quantity\x18\x07 \x01(\x05\x12\r\n\x05price\x18\x08 \x01(\x01\x12\x0f\n\x07gateway\x18\t \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\n \x01(\t\x12\x17\n\x0f\x62roker_order_id\x18\x0b \x01(\t\x12\x15\n\revent_time_ms\x18\x0c \x01(\x03\x12\x0f\n\x07message\x18\r \x01(\t\"\x9a\x01\n\x0cGatewayFrame\x12)\n\x05ready\x18\x01 \x01(\x0b\x32\x18.omsgateway.ReadyMessageH\x00\x12+\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x18.omsgateway.OrderCommandH\x00\x12\'\n\x05\x65vent\x18\x03 \x01(\x0b\x32\x16.omsgateway.OrderEventH\x00\x42\t\n\x07payload*`\n\nActionType\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x0e\n\nACTION_NEW\x10\x01\x12\x17\n\x13\x41\x43TION_MODIFY_PRICE\x10\x02\x12\x11\n\rACTION_CANCEL\x10\x03\x32R\n\rGatewayBridge\x12\x41\n\x07\x43onnect\x12\x18.omsgateway.GatewayFrame\x1a\x18.omsgateway.GatewayFrame(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oms_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIONTYPE']._serialized_start=711
  _globals['_ACTIONTYPE']._serialized_end=807
  _globals['_READYMESSAGE']._serialized_start=33
  _globals['_READYMESSAGE']._serialized_end=113
  _globals['_ORDERCOMMAND']._serialized_start=116
  _globals['_ORDERCOMMAND']._serialized_end=299
  _globals['_ORDEREVENT']._serialized_start=302
  _globals['_ORDEREVENT']._serialized_end=552
  _globals['_GATEWAYFRAME']._serialized_start=555
  _globals['_GATEWAYFRAME']._serialized_end=709
  _globals['_GATEWAYBRIDGE']._serialized_start=809
  _globals['_GATEWAYBRIDGE']._serialized_end=891
# @@protoc_insertion_point(module_scope)
